# paths (need if not get latest)
video_tokenizer_path: 
latent_actions_path: 
dynamics_path: 
use_latest_checkpoints: true

# inference params
dataset: ZELDA
preload_ratio:
device: cuda # make sure to use correct device
generation_steps: 4
context_window: 3
fps: 2
temperature: 0.0 # 0 is argmax
teacher_forced: false # for testing/dev
prediction_horizon: 1 # how many masked frames to append and decode at a time
decode_steps: 16 # maskgit iterative decode steps

# action selection modes (lower takes priority)
use_actions: false # use random actions
use_gt_actions: false # use lam-inferred actions
use_interactive_mode: false # use user-inputted actions

# reproducibility controls
seed:
sample_index:

# inference acceleration
amp: false
tf32: false
compile: false
