# wandb
use_wandb: true
wandb_project: tinyworlds

# dataset
dataset: ZELDA
preload_ratio: 0.5

# shared model params
patch_size: 4
context_length: 4
frame_size: 128
latent_dim: 5 # for video tokenizer
num_bins: 4 # for video tokenizer
n_actions: 16

# performance
amp: true
tf32: true
compile: false

# distributed launch (torchrun)
distributed: 
  use_ddp: True
  use_fsdp: False
  reshard_after_forward: False
nproc_per_node: 2 # how many GPUs per node
standalone: true # if we're using one node, this eliminates extraneous processes

# stage configs
video_tokenizer_config: configs/video_tokenizer.yaml
latent_actions_config: configs/latent_actions.yaml
dynamics_config: configs/dynamics.yaml

# which stages to run
run_video_tokenizer: false
run_latent_actions: false
run_dynamics: true
